### ISSUE TITLE
What do I do with the private key?

### ISSUE THREAD

**Issue by pzaszp** [TheDen/btc-heist#3]
I know this is probably a stupid question, but I ended up getting a private key linked to a bitcoin public address. https://www.blockchain.com/btc/address/3HNKev43v3EW6Biu5TwTVgKrDCzPCjzpCH

I can't put the address into Electrum or anything like that, because it's encrypted (maybe). If anyone could help me that'd be really great. Thanks!

**Comment by xWxStore** [comment]
@pzaszp i think i can help pzaszp

**Comment by SebbeDuck** [comment]
Did you actually get that address & priv key?
