### ISSUE TITLE
New line character in publist

### ISSUE THREAD

**Issue by charlesharvey** [TheDen/btc-heist#5]
When i inspect publist it shows addresses with a newline character at the end eg
'1HLvaTs3zR3oev9ya7Pzp3GB9Gqfg6XYJT\n'

Wont` '1HLvaTs3zR3oev9ya7Pzp3GB9Gqfg6XYJT' in publist` always return False because theres no newline?
Sorry, am a beginner with python

**Comment by TheDen** [comment]
You're right, prior when I tested it worked, but I didn't due my due diligence with the refactoring. Apologies. I fixed this in the latest [commit](https://github.com/TheDen/btc-heist/commit/2214d62267f23ec73599193a6afa278e0916712c)
